### ISSUE TITLE
YOUTUBE API

### ISSUE THREAD

**Issue by JonSno29** [JonSno29/Number_1_Coders#25]
* Make sure to get authentication right first since the API counts "unauthorized" requests in the quota. That means 6 failed upload requests = 9600 quota = retry in 24h. Use something lighter like a [list(my channel) request](https://developers.google.com/youtube/v3/docs/channels/list).

youtube.js

fetch("")
.then((result)=>{
    return result.json()
}).then((data)=>{
    console.log(data)
    let videos = data.items  
    let videoContainer = document.querySelector(".youtube-container")
    for(video of videos){
        videoContainer.innerHTML += 
            <img src="${video.snippet.thumbnails.default.url}"></img>
            }   
});

youtube.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CODIO VIDEO</title>
    <script type="text/javascript" src="youtube.js"></script>

</head>
<body>
    <h1>INTERVIEW PREPERATION VIDEOS</h1>
</body>
</html>

**Comment by Huntken26** [comment]
Jon completed the youtube api
